def randomgroup():
    import random
    list=["申思远","潘虹阳","张泽阳","明子涵","张乐","王方铭","黄俊杰","张奥","陈彦博","曾天泽","高源","孙泽林","卡米力·万里","杨凌杰","焦博君","刘清扬","余沛瑶","赵怡然","张璇","唐予珊","金芝贤","陈艺嘉"]
    a=random.choice(list)
    list.remove(a)
    b=random.choice(list)
    list.remove(b)
    c=random.choice(list)
    list.remove(c)
    d=random.choice(list)
    list.remove(d)
    e=random.choice(list)
    list.remove(e)
    f=random.choice(list)
    list.remove(f)
    g=random.choice(list)
    list.remove(g)
    h=random.choice(list)
    list.remove(h)
    i=random.choice(list)
    list.remove(i)
    j=random.choice(list)
    list.remove(j)
    k=random.choice(list)
    list.remove(k)
    l=random.choice(list)
    list.remove(l)
    m=random.choice(list)
    list.remove(m)
    n=random.choice(list)
    list.remove(n)
    o=random.choice(list)
    list.remove(o)
    p=random.choice(list)
    list.remove(p)
    q=random.choice(list)
    list.remove(q)
    r=random.choice(list)
    list.remove(r)
    s=random.choice(list)
    list.remove(s)
    t=random.choice(list)
    list.remove(t)
    u=random.choice(list)
    list.remove(u)
    v=random.choice(list)
    list.remove(v)
    print("第一组成员:{0}, {1}, {2}, {3}".format(a,b,c,d))
    print("第二组成员:{0}, {1}, {2}, {3}".format(e,f,g,h))
    print("第三组成员:{0}, {1}, {2}, {3}".format(i,j,k,l))
    print("第四组成员:{0}, {1}, {2}, {3}, {4}".format(m,n,o,p,q))
    print("第五组成员:{0}, {1}, {2}, {3}, {4}".format(r,s,t,u,v))
